# General Configuration
project:
  name: "Gift Recommendation Platform"
  version: "1.0.0"

paths:
  data_raw: "data/raw"
  data_processed: "data/processed"
  models: "data/models"

logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: "logs/app.log"